#include "SilverLiningOpenGLPreamble.h"

namespace SilverLining
{
PFNGLGENFRAMEBUFFERSEXTPROC glGenFramebuffersEXT = 0;
PFNGLBINDFRAMEBUFFEREXTPROC glBindFramebufferEXT = 0;
PFNGLFRAMEBUFFERTEXTURE2DEXTPROC glFramebufferTexture2DEXT = 0;
PFNGLGENERATEMIPMAPEXTPROC glGenerateMipmapEXT = 0;
PFNGLDELETEFRAMEBUFFERSEXTPROC glDeleteFramebuffersEXT = 0;
PFNGLCHECKFRAMEBUFFERSTATUSEXTPROC glCheckFramebufferStatusEXT = 0;

PFNGLBLENDEQUATIONEXTPROC glBlendEquationEXT = 0;

PFNGLGENBUFFERSARBPROC glGenBuffersARB = 0;
PFNGLBINDBUFFERARBPROC glBindBufferARB = 0;
PFNGLBUFFERDATAARBPROC glBufferDataARB = 0;
PFNGLMAPBUFFERARBPROC glMapBufferARB = 0;
PFNGLISBUFFERARBPROC glIsBufferARB = 0;
PFNGLBUFFERSUBDATAARBPROC glBufferSubDataARB = 0;
PFNGLGETBUFFERSUBDATAARBPROC glGetBufferSubDataARB = 0;
PFNGLUNMAPBUFFERARBPROC glUnmapBufferARB = 0;
PFNGLDELETEBUFFERSARBPROC glDeleteBuffersARB = 0;
PFNGLPOINTPARAMETERINVPROC glPointParameteriNV = 0;
#ifndef NATIVE_1_3
PFNGLACTIVETEXTUREARBPROC glActiveTexture = 0;
PFNGLCLIENTACTIVETEXTUREARBPROC glClientActiveTexture = 0;
#endif
#ifndef NATIVE_1_2
PFNGLTEXIMAGE3DPROC glTexImage3D = 0;
PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D = 0;
#endif
PFNGLBUFFERADDRESSRANGENVPROC glBufferAddressRangeNV = 0;
PFNGLVERTEXFORMATNVPROC glVertexFormatNV = 0;
PFNGLCOLORFORMATNVPROC glColorFormatNV = 0;
PFNGLTEXCOORDFORMATNVPROC glTexCoordFormatNV = 0;
PFNGLGETBUFFERPARAMETERUI64VNVPROC glGetBufferParameterui64vNV = 0;
PFNGLISBUFFERRESIDENTNVPROC glIsBufferResidentNV = 0;
PFNGLMAKEBUFFERRESIDENTNVPROC glMakeBufferResidentNV = 0;
PFNGLMAKEBUFFERNONRESIDENTNVPROC glMakeBufferNonResidentNV = 0;
PFNGLISNAMEDBUFFERRESIDENTNVPROC glIsNamedBufferResidentNV = 0;
PFNGLMAKENAMEDBUFFERRESIDENTNVPROC glMakeNamedBufferResidentNV = 0;
PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC glMakeNamedBufferNonResidentNV = 0;
PFNGLGENQUERIESARBPROC glGenQueriesARB = 0;
PFNGLDELETEQUERIESARBPROC glDeleteQueriesARB = 0;
PFNGLBEGINQUERYARBPROC glBeginQueryARB = 0;
PFNGLENDQUERYARBPROC glEndQueryARB = 0;
PFNGLGETQUERYOBJECTUIVARBPROC glGetQueryObjectuivARB = 0;
PFNGLCLAMPCOLORARBPROC glClampColorARB = 0;
PFNGLCREATESHADEROBJECTARBPROC glCreateShaderObjectARB = 0;
PFNGLSHADERSOURCEARBPROC glShaderSourceARB = 0;
PFNGLCOMPILESHADERARBPROC glCompileShaderARB = 0;
PFNGLCREATEPROGRAMOBJECTARBPROC glCreateProgramObjectARB = 0;
PFNGLATTACHOBJECTARBPROC glAttachObjectARB = 0;
PFNGLLINKPROGRAMARBPROC glLinkProgramARB = 0;
PFNGLUSEPROGRAMOBJECTARBPROC glUseProgramObjectARB = 0;
PFNGLDETACHOBJECTARBPROC glDetachObjectARB = 0;
PFNGLDELETEOBJECTARBPROC glDeleteObjectARB = 0;
PFNGLGETUNIFORMLOCATIONARBPROC glGetUniformLocationARB = 0;
PFNGLUNIFORM4FARBPROC glUniform4fARB = 0;
PFNGLUNIFORMMATRIX4FVARBPROC glUniformMatrix4fvARB = 0;
PFNGLGETOBJECTPARAMETERIVARBPROC glGetObjectParameterivARB = 0;
PFNGLGETINFOLOGARBPROC glGetInfoLogARB = 0;
PFNGLUNIFORM1IARBPROC glUniform1iARB = 0;
PFNGLGETHANDLEARBPROC glGetHandleARB = 0;
PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers = 0;
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer = 0;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D = 0;
PFNGLGENERATEMIPMAPPROC glGenerateMipmap = 0;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers = 0;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus = 0;
PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers = 0;
PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer = 0;
PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer = 0;
PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage = 0;
PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers = 0;
PFNGLDEPTHRANGEDNVPROC glDepthRangedNV = 0;

PFNGLGETNAMEDBUFFERPARAMETERUI64VNVPROC glGetNamedBufferParameterui64vNV = 0;

PFNGLVERTEXATTRIBFORMATNVPROC glVertexAttribFormatNV = 0;
PFNGLMULTIDRAWELEMENTSINDIRECTBINDLESSNVPROC glMultiDrawElementsIndirectBindlessNV = 0;

PFNGLGETTEXTUREHANDLEARBPROC glGetTextureHandleARB = 0;
PFNGLMAKETEXTUREHANDLERESIDENTARBPROC glMakeTextureHandleResidentARB = 0;
PFNGLMAKETEXTUREHANDLENONRESIDENTARBPROC glMakeTextureHandleNonResidentARB = 0;
PFNGLISTEXTUREHANDLERESIDENTARBPROC glIsTextureHandleResidentARB = 0;

#ifndef NATIVE_1_4
PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate = 0;
#endif

#ifndef NATIVE_2_0
PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate = 0;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray = 0;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray = 0;
#endif

#ifndef NATIVE_3_0
PFNGLBINDBUFFERBASEPROC glBindBufferBase = 0;
#endif

#ifndef NATIVE_3_1
PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced = 0;
PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced = 0;
#endif

#ifndef NATIVE_4_1
PFNGLPROGRAMUNIFORM1IPROC glProgramUniform1i = 0;

PFNGLPROGRAMUNIFORM1FPROC glProgramUniform1f = 0;
PFNGLPROGRAMUNIFORM2FPROC glProgramUniform2f = 0;
PFNGLPROGRAMUNIFORM3FPROC glProgramUniform3f = 0;
PFNGLPROGRAMUNIFORM4FPROC glProgramUniform4f = 0;

PFNGLPROGRAMUNIFORM1DPROC glProgramUniform1d = 0;
PFNGLPROGRAMUNIFORM2DPROC glProgramUniform2d = 0;
PFNGLPROGRAMUNIFORM3DPROC glProgramUniform3d = 0;
PFNGLPROGRAMUNIFORM4DPROC glProgramUniform4d = 0;

PFNGLPROGRAMUNIFORMMATRIX4FVPROC glProgramUniformMatrix4fv = 0;
PFNGLPROGRAMUNIFORMMATRIX3FVPROC glProgramUniformMatrix3fv = 0;
#endif

#ifndef NATIVE_4_3
PFNGLPUSHDEBUGGROUPPROC glPushDebugGroup = 0;
PFNGLPOPDEBUGGROUPPROC glPopDebugGroup = 0;
PFNGLOBJECTLABELPROC glObjectLabel = 0;
PFNGLGETOBJECTLABELPROC glGetObjectLabel = 0;
PFNGLOBJECTPTRLABELPROC glObjectPtrLabel = 0;
PFNGLGETOBJECTPTRLABELPROC glGetObjectPtrLabel = 0;

PFNGLGETPROGRAMINTERFACEIVPROC glGetProgramInterfaceiv = 0;
PFNGLGETPROGRAMRESOURCEIVPROC glGetProgramResourceiv = 0;
PFNGLGETPROGRAMRESOURCENAMEPROC glGetProgramResourceName = 0;

PFNGLBINDVERTEXBUFFERPROC glBindVertexBuffer = 0;
PFNGLVERTEXATTRIBFORMATPROC glVertexAttribFormat = 0;
PFNGLVERTEXATTRIBBINDINGPROC glVertexAttribBinding = 0;
#endif

#ifndef NATIVE_4_5
PFNGLNAMEDBUFFERDATAPROC glNamedBufferData  = 0;
PFNGLNAMEDBUFFERSUBDATAPROC glNamedBufferSubData = 0;
PFNGLGETNAMEDBUFFERPARAMETERIVPROC glGetNamedBufferParameteriv = 0;
PFNGLGETNAMEDBUFFERSUBDATAPROC glGetNamedBufferSubData = 0;

PFNGLNAMEDBUFFERSTORAGEPROC glNamedBufferStorage = 0;
PFNGLMAPNAMEDBUFFERRANGEPROC glMapNamedBufferRange = 0;
PFNGLUNMAPNAMEDBUFFERPROC glUnmapNamedBuffer = 0;
#endif
}
