#include "SilverLiningOpenGLPreamble.h"

namespace SilverLining
{
PFNGLGETBUFFERPARAMETERUI64VNVPROC glGetBufferParameterui64vNV= 0;
PFNGLGETNAMEDBUFFERPARAMETERUI64VNVPROC glGetNamedBufferParameterui64vNV= 0;

PFNGLISBUFFERRESIDENTNVPROC glIsBufferResidentNV= 0;
PFNGLMAKEBUFFERRESIDENTNVPROC glMakeBufferResidentNV= 0;
PFNGLMAKEBUFFERNONRESIDENTNVPROC glMakeBufferNonResidentNV= 0;

PFNGLISNAMEDBUFFERRESIDENTNVPROC glIsNamedBufferResidentNV= 0;
PFNGLMAKENAMEDBUFFERRESIDENTNVPROC glMakeNamedBufferResidentNV= 0;
PFNGLMAKENAMEDBUFFERNONRESIDENTNVPROC glMakeNamedBufferNonResidentNV= 0;

PFNGLVERTEXATTRIBFORMATNVPROC glVertexAttribFormatNV= 0;
PFNGLBUFFERADDRESSRANGENVPROC glBufferAddressRangeNV= 0;
PFNGLBINDVERTEXBUFFERPROC glBindVertexBuffer = 0;
PFNGLVERTEXATTRIBFORMATPROC glVertexAttribFormat = 0;
PFNGLVERTEXATTRIBBINDINGPROC glVertexAttribBinding = 0;
PFNGLMULTIDRAWELEMENTSINDIRECTBINDLESSNVPROC glMultiDrawElementsIndirectBindlessNV = 0;

PFNGLGETTEXTUREHANDLEARBPROC glGetTextureHandleARB= 0;
PFNGLGETTEXTURESAMPLERHANDLEARBPROC glGetTextureSamplerHandleARB= 0;
PFNGLMAKETEXTUREHANDLERESIDENTARBPROC glMakeTextureHandleResidentARB= 0;
PFNGLMAKETEXTUREHANDLENONRESIDENTARBPROC glMakeTextureHandleNonResidentARB= 0;
PFNGLISTEXTUREHANDLERESIDENTARBPROC glIsTextureHandleResidentARB= 0;
PFNGLUNIFORMHANDLEUI64ARBPROC glUniformHandleui64ARB= 0;
PFNGLUNIFORMHANDLEUI64VARBPROC glUniformHandleui64vARB= 0;
PFNGLPROGRAMUNIFORMHANDLEUI64ARBPROC glProgramUniformHandleui64ARB= 0;
PFNGLPROGRAMUNIFORMHANDLEUI64VARBPROC glProgramUniformHandleui64vARB= 0;

PFNGLGETOBJECTPARAMETERIVARBPROC glGetObjectParameterivARB= 0;
PFNGLGETINFOLOGARBPROC glGetInfoLogARB= 0;

PFNGLDEPTHRANGEDNVPROC glDepthRangedNV = 0;

#ifndef NATIVE_4_5
PFNGLGENERATETEXTUREMIPMAPPROC glGenerateTextureMipmap= 0;
PFNGLNAMEDBUFFERDATAPROC glNamedBufferData= 0;
PFNGLNAMEDBUFFERSUBDATAPROC glNamedBufferSubData= 0;
PFNGLGETNAMEDBUFFERSUBDATAPROC glGetNamedBufferSubData = 0;
PFNGLGETNAMEDBUFFERPARAMETERIVPROC glGetNamedBufferParameteriv= 0;
PFNGLTEXTUREPARAMETERIPROC glTextureParameteri= 0;
PFNGLGETTEXTUREPARAMETERIVPROC glGetTextureParameteriv= 0;
PFNGLCREATEBUFFERSPROC glCreateBuffers= 0;
PFNGLCREATESAMPLERSPROC glCreateSamplers= 0;

PFNGLNAMEDBUFFERSTORAGEPROC glNamedBufferStorage = 0;
PFNGLMAPNAMEDBUFFERRANGEPROC glMapNamedBufferRange = 0;
PFNGLUNMAPNAMEDBUFFERPROC glUnmapNamedBuffer = 0;

#endif

#ifndef NATIVE_4_4
PFNGLBUFFERSTORAGEPROC glBufferStorage= 0;
#endif

#ifndef NATIVE_4_3
PFNGLMULTIDRAWARRAYSINDIRECTPROC glMultiDrawArraysIndirect= 0;
PFNGLMULTIDRAWELEMENTSINDIRECTPROC glMultiDrawElementsIndirect= 0;

PFNGLDEBUGMESSAGECONTROLPROC glDebugMessageControl= 0;
PFNGLDEBUGMESSAGEINSERTPROC glDebugMessageInsert= 0;
PFNGLDEBUGMESSAGECALLBACKPROC glDebugMessageCallback= 0;
PFNGLGETDEBUGMESSAGELOGPROC glGetDebugMessageLog= 0;
PFNGLPUSHDEBUGGROUPPROC glPushDebugGroup= 0;
PFNGLPOPDEBUGGROUPPROC glPopDebugGroup= 0;
PFNGLOBJECTLABELPROC glObjectLabel= 0;
PFNGLGETOBJECTLABELPROC glGetObjectLabel= 0;
PFNGLOBJECTPTRLABELPROC glObjectPtrLabel= 0;
PFNGLGETOBJECTPTRLABELPROC glGetObjectPtrLabel= 0;

PFNGLGETPROGRAMINTERFACEIVPROC glGetProgramInterfaceiv = 0;
PFNGLGETPROGRAMRESOURCEIVPROC glGetProgramResourceiv = 0;
PFNGLGETPROGRAMRESOURCENAMEPROC glGetProgramResourceName = 0;
#endif

#ifndef NATIVE_4_1
PFNGLPROGRAMUNIFORM1IPROC glProgramUniform1i= 0;

PFNGLPROGRAMUNIFORM1FPROC glProgramUniform1f= 0;
PFNGLPROGRAMUNIFORM2FPROC glProgramUniform2f= 0;
PFNGLPROGRAMUNIFORM3FPROC glProgramUniform3f= 0;
PFNGLPROGRAMUNIFORM4FPROC glProgramUniform4f= 0;

PFNGLPROGRAMUNIFORM1DPROC glProgramUniform1d= 0;
PFNGLPROGRAMUNIFORM2DPROC glProgramUniform2d= 0;
PFNGLPROGRAMUNIFORM3DPROC glProgramUniform3d= 0;
PFNGLPROGRAMUNIFORM4DPROC glProgramUniform4d= 0;

PFNGLPROGRAMUNIFORMMATRIX4FVPROC glProgramUniformMatrix4fv= 0;
PFNGLPROGRAMUNIFORMMATRIX3FVPROC glProgramUniformMatrix3fv= 0;
#endif

#ifndef NATIVE_4_0
PFNGLUNIFORM1DPROC glUniform1d= 0;
PFNGLUNIFORM2DPROC glUniform2d= 0;
PFNGLUNIFORM3DPROC glUniform3d= 0;
PFNGLUNIFORM4DPROC glUniform4d= 0;

PFNGLDRAWARRAYSINDIRECTPROC glDrawArraysIndirect= 0;
PFNGLDRAWELEMENTSINDIRECTPROC glDrawElementsIndirect= 0;
#endif

#ifndef NATIVE_3_3
PFNGLGENSAMPLERSPROC            glGenSamplers= 0;
PFNGLDELETESAMPLERSPROC         glDeleteSamplers= 0;
PFNGLISSAMPLERPROC              glIsSampler= 0;
PFNGLBINDSAMPLERPROC            glBindSampler= 0;

PFNGLSAMPLERPARAMETERIPROC       glSamplerParameteri= 0;
PFNGLSAMPLERPARAMETERIVPROC      glSamplerParameteriv= 0;
PFNGLSAMPLERPARAMETERFPROC       glSamplerParameterf= 0;
PFNGLSAMPLERPARAMETERFVPROC      glSamplerParameterfv= 0;
PFNGLSAMPLERPARAMETERIIVPROC     glSamplerParameterIiv= 0;
PFNGLSAMPLERPARAMETERIUIVPROC    glSamplerParameterIuiv= 0;
PFNGLGETSAMPLERPARAMETERIVPROC   glGetSamplerParameteriv= 0;
PFNGLGETSAMPLERPARAMETERIIVPROC  glGetSamplerParameterIiv= 0;
PFNGLGETSAMPLERPARAMETERFVPROC   glGetSamplerParameterfv= 0;
PFNGLGETSAMPLERPARAMETERIUIVPROC glGetSamplerParameterIuiv= 0;
PFNGLVERTEXATTRIBDIVISORARBPROC glVertexAttribDivisor= 0;
#endif

#ifndef NATIVE_3_2
PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers= 0;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers= 0;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D= 0;
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer= 0;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus= 0;
PFNGLCLIENTWAITSYNCPROC glClientWaitSync= 0;
PFNGLFENCESYNCPROC glFenceSync= 0;
PFNGLDELETESYNCPROC glDeleteSync= 0;
#endif

#ifndef NATIVE_3_1
PFNGLGETUNIFORMBLOCKINDEXPROC glGetUniformBlockIndex= 0;
PFNGLUNIFORMBLOCKBINDINGPROC glUniformBlockBinding= 0;
PFNGLGETACTIVEUNIFORMBLOCKIVPROC glGetActiveUniformBlockiv= 0;
PFNGLGETACTIVEUNIFORMSIVPROC glGetActiveUniformsiv= 0;
PFNGLGETUNIFORMINDICESPROC glGetUniformIndices= 0;

PFNGLDRAWARRAYSINSTANCEDPROC glDrawArraysInstanced = 0;
PFNGLDRAWELEMENTSINSTANCEDPROC glDrawElementsInstanced = 0;

#endif

#ifndef NATIVE_3_0
PFNGLGENERATEMIPMAPPROC glGenerateMipmap= 0;
PFNGLDELETEVERTEXARRAYSPROC glDeleteVertexArrays= 0;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays= 0;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray= 0;
PFNGLGETSTRINGIPROC glGetStringi= 0;
PFNGLBINDBUFFERBASEPROC glBindBufferBase= 0;

PFNGLBINDFRAGDATALOCATIONPROC glBindFragDataLocation = 0;
PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate = 0;
PFNGLTEXIMAGE3DPROC glTexImage3D = 0;
PFNGLTEXSUBIMAGE3DPROC glTexSubImage3D = 0;

PFNGLISRENDERBUFFERPROC glIsRenderbuffer = 0;
PFNGLBINDBUFFERPROC glBindRenderbuffer = 0;
PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers = 0;
PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers = 0;
PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage = 0;
PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer = 0;
#endif

#ifndef NATIVE_1_3
PFNGLACTIVETEXTUREPROC glActiveTexture= 0;
PFNGLCLIENTACTIVETEXTUREPROC glClientActiveTexture= 0;
#endif

#ifndef NATIVE_1_4
PFNGLPOINTPARAMETERFPROC glPointParameterf= 0;
PFNGLPOINTPARAMETERFVPROC glPointParameterfv= 0;
PFNGLMULTIDRAWARRAYSPROC glMultiDrawArrays= 0;
PFNGLMULTIDRAWELEMENTSPROC glMultiDrawElements= 0;
#endif

#ifndef NATIVE_1_5
PFNGLGENQUERIESPROC glGenQueries = 0;
PFNGLDELETEQUERIESPROC glDeleteQueries = 0;
PFNGLISQUERYPROC glIsQuery = 0;
PFNGLBEGINQUERYPROC glBeginQuery = 0;
PFNGLENDQUERYPROC glEndQuery = 0;
PFNGLGETQUERYIVPROC glGetQueryiv = 0;
PFNGLGETQUERYOBJECTIVPROC glGetQueryObjectiv = 0;
PFNGLGETQUERYOBJECTUIVPROC glGetQueryObjectuiv = 0;

PFNGLISBUFFERPROC glIsBuffer = 0;
PFNGLGETBUFFERPARAMETERIVPROC glGetBufferParameteriv = 0;
#endif

#ifndef NATIVE_2_0
PFNGLGETUNIFORMLOCATIONPROC glGetUniformLocation= 0;
PFNGLUNIFORM1IPROC glUniform1i= 0;
PFNGLUSEPROGRAMPROC glUseProgram= 0;
PFNGLUNIFORM1FPROC glUniform1f= 0;
PFNGLUNIFORM2FPROC glUniform2f= 0;
PFNGLUNIFORM3FPROC glUniform3f= 0;
PFNGLUNIFORM4FPROC glUniform4f= 0;
PFNGLDELETEBUFFERSPROC glDeleteBuffers= 0;
PFNGLDETACHSHADERPROC glDetachShader= 0;
PFNGLGETSHADERIVPROC glGetShaderiv= 0;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog= 0;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog= 0;
PFNGLGETSHADERSOURCEPROC glGetShaderSource= 0;
PFNGLCREATESHADERPROC glCreateShader= 0;
PFNGLCOMPILESHADERPROC glCompileShader= 0;
PFNGLSHADERSOURCEPROC glShaderSource= 0;
PFNGLCREATEPROGRAMPROC glCreateProgram= 0;
PFNGLATTACHSHADERPROC glAttachShader= 0;
PFNGLLINKPROGRAMPROC glLinkProgram= 0;
PFNGLGETPROGRAMIVPROC glGetProgramiv= 0;
PFNGLGETATTRIBLOCATIONPROC glGetAttribLocation= 0;
PFNGLUNIFORMMATRIX4FVPROC glUniformMatrix4fv= 0;
PFNGLUNIFORMMATRIX3FVPROC glUniformMatrix3fv= 0;
PFNGLBINDBUFFERPROC glBindBuffer= 0;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer= 0;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray= 0;
PFNGLGENBUFFERSPROC glGenBuffers= 0;
PFNGLBUFFERDATAPROC glBufferData= 0;
PFNGLDELETESHADERPROC glDeleteShader= 0;
PFNGLDELETEPROGRAMPROC glDeleteProgram= 0;
PFNGLMAPBUFFERPROC glMapBuffer= 0;
PFNGLUNMAPBUFFERPROC glUnmapBuffer= 0;
PFNGLDISABLEVERTEXATTRIBARRAYPROC glDisableVertexAttribArray= 0;
PFNGLBUFFERSUBDATAPROC glBufferSubData= 0;
PFNGLGETBUFFERSUBDATAPROC glGetBufferSubData = 0;
PFNGLMAPBUFFERRANGEPROC glMapBufferRange= 0;
PFNGLISSHADERPROC glIsShader= 0;
PFNGLDRAWBUFFERSPROC glDrawBuffers= 0;
#endif

PFNGLGENFRAMEBUFFERSPROC glGenFramebuffersEXT = 0;
PFNGLBINDFRAMEBUFFERPROC glBindFramebufferEXT = 0;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2DEXT = 0;
PFNGLGENERATEMIPMAPPROC glGenerateMipmapEXT = 0;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffersEXT = 0;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatusEXT = 0;
PFNGLBLENDEQUATIONEXTPROC glBlendEquationEXT = 0;
}